version: 2

builds:
  - main: .
    binary: yawc
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: ['tar.gz']
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ['zip']

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
